export const QUIZ_BANK = [
  { id: 1, question: 'İnsanlık tarihinde "Neolitik Devrim" kavramını ilk kez ortaya atan bilim insanı kimdir?', options: ['Lewis Binford', 'V. Gordon Childe', 'Ian Hodder', 'Robert Braidwood'], answer: 1 },
  { id: 2, question: 'Anadolu’da obsidiyen ticaretinin merkezi sayılan Neolitik yerleşim hangisidir?', options: ['Çayönü', 'Aşıklı Höyük', 'Hacılar', 'Hallan Çemi'], answer: 1 },
  { id: 3, question: 'Göbeklitepe T biçimli dikilitaş üslubu hangi dönemi yansıtır?', options: ['Epipaleolitik / Çanak Çömleksiz Neolitik A', 'Geç Neolitik', 'Kalkolitik', 'Erken Tunç Çağı'], answer: 0 },
  { id: 4, question: 'Mezopotamya’da yazının ilk kez kullanıldığı dönem hangisidir?', options: ['Ubeyd', 'Uruk', 'Cemdet Nasr', 'Akad'], answer: 1 },
  { id: 5, question: 'Kültepe tabletleri neden dönüm noktasıdır?', options: ['İlk tapınak planlarını içermesi', 'Anadolu’nun yazılı tarihe geçişini sağlaması', 'Hitit başkentini belirtmesi', 'Demir kullanımını tarif etmesi'], answer: 1 },
  { id: 6, question: 'Hitit devlet yapısında soylular meclisinin adı nedir?', options: ['Tavananna', 'Pankuş', 'Labarna', 'Ziti'], answer: 1 },
  { id: 7, question: 'Urartu başkenti Tuşpa günümüzde hangi şehirdedir?', options: ['Erzurum', 'Van', 'Kars', 'Erzincan'], answer: 1 },
  { id: 8, question: 'Frig sanatında mobilyacılıkta kullanılan geçme tekniği?', options: ['Fibula', 'Tümülüs', 'Mevduat', 'Kakmacılık / Kündekari benzeri'], answer: 3 },
  { id: 9, question: 'Lidya’nın ilk sikkelerinin temel amacı neydi?', options: ['Halkın zenginleşmesi', 'Paralı asker ödemelerini standartlaştırmak', 'Dış ticareti durdurmak', 'Tapınak vergilerini toplamak'], answer: 1 },
  { id: 10, question: 'Geç Hititlerde kapı girişlerini koruyan aslan/sfenks heykellerine ne ad verilir?', options: ['Megaron', 'Ortostat', 'Stela', 'Karum'], answer: 1 },
  { id: 11, question: 'Yunan tapınak mimarisinde sütun başlığının üzerindeki yatay öğe?', options: ['Arşitrav (Epistil)', 'Friz', 'Geison', 'Timpanon'], answer: 0 },
  { id: 12, question: 'Dor düzeninde metoplar arasında kalan üç yivli bölüm?', options: ['Volüt', 'Triglif', 'Abakus', 'Echinus'], answer: 1 },
  { id: 13, question: 'Kontrapost tekniğinin erken ünlü örneklerinden heykel?', options: ['Kouros', 'Kritios Oğlu', 'Doryphoros', 'Laocoön'], answer: 1 },
  { id: 14, question: 'Helenistik Dönem’in başlangıcı kabul edilen olay?', options: ['Peloponnesos Savaşları bitişi', 'Büyük İskender’in ölümü', 'Augustus’un imparator olması', 'Pers işgali'], answer: 1 },
  { id: 15, question: 'Roma mimarisinde antik betonun adı?', options: ['Opus Reticulatum', 'Opus Caementicium', 'Opus Sectile', 'Opus Tessellatum'], answer: 1 },
  { id: 16, question: 'Roma tiyatrosunda seyircilerin oturduğu basamaklı kısım?', options: ['Orchestra', 'Skene', 'Cavea', 'Vomitorium'], answer: 2 },
  { id: 17, question: 'Atina Akropolisi’nde Karyatidli tapınak?', options: ['Parthenon', 'Erechtheion', 'Nike Tapınağı', 'Propylaia'], answer: 1 },
  { id: 18, question: 'Roma planlamasında kuzey-güney ana cadde?', options: ['Decumanus Maximus', 'Cardo Maximus', 'Forum', 'Insula'], answer: 1 },
  { id: 19, question: 'Siyah figürden kırmızı figüre geçiş yaklaşık ne zaman?', options: ['MÖ 7. yy sonu', 'MÖ 530 civarı', 'MÖ 4. yy', 'MS 1. yy'], answer: 1 },
  { id: 20, question: 'Pompeii duvar resimlerinde illüzyonist üslup kaçıncı stil?', options: ['1. Stil', '2. Stil', '3. Stil', '4. Stil'], answer: 1 },
  { id: 21, question: 'Tabakalaşma yasasına göre en alt tabaka?', options: ['En modern tabaka', 'En eski tabaka', 'Tarihlendirilemez', 'Kesin Roma'], answer: 1 },
  { id: 22, question: 'Dendrokronoloji hangi materyalde yapılır?', options: ['Kemik', 'Seramik', 'Ağaç halkaları', 'Taş'], answer: 2 },
  { id: 23, question: 'Karbon-14 yöntemi en fazla kaç yıla kadar sağlıklı?', options: ['5.000 yıl', '50.000-60.000 yıl', '1 milyon yıl', '10 milyon yıl'], answer: 1 },
  { id: 24, question: 'Süreçsel Arkeoloji’nin öncüsü kimdir?', options: ['Ian Hodder', 'Lewis Binford', 'Heinrich Schliemann', 'Arthur Evans'], answer: 1 },
  { id: 25, question: 'Seramik yoğunluğuna göre yerleşim sınırı belirleme yöntemi?', options: ['Sondaj', 'Survey', 'Stratigrafi', 'Tipoloji'], answer: 1 },
  { id: 26, question: 'Önceden planlanmış formda yonga çıkarma tekniği?', options: ['Levallois tekniği', 'El baltası tekniği', 'Mikrolit tekniği', 'Baskı tekniği'], answer: 0 },
  { id: 27, question: 'In-situ neyi ifade eder?', options: ['Laboratuvarda inceleme', 'Buluntunun orijinal konumu', 'Sahte buluntu', 'Dağınık yüzey malzemesi'], answer: 1 },
  { id: 28, question: 'Gelidonya Burnu batığı kazısını yöneten isim?', options: ['Robert Ballard', 'George Bass', 'Jacques Cousteau', 'Cemal Pulak'], answer: 1 },
  { id: 29, question: 'Seramik form/bezeme gruplandırmasına ne denir?', options: ['Epigrafi', 'Tipoloji', 'Numismatik', 'Antropoloji'], answer: 1 },
  { id: 30, question: 'Post-Süreçsel arkeolojinin önemli savunucusu?', options: ['James Mellaart', 'Ian Hodder', 'Colin Renfrew', 'Michael Schiffer'], answer: 1 },
  { id: 31, question: 'Roma mitolojisinde Hermes’in karşılığı?', options: ['Mars', 'Merkür', 'Neptün', 'Jüpiter'], answer: 1 },
  { id: 32, question: 'Sikke üzerindeki yazılara ne denir?', options: ['Epigraf', 'Lejand', 'Kabartma', 'Mühür'], answer: 1 },
  { id: 33, question: 'Sikkenin ön yüzü?', options: ['Revers', 'Avers', 'Exergue', 'Kondisyon'], answer: 1 },
  { id: 34, question: 'Epigrafi bilimi neyi inceler?', options: ['Sikkeleri', 'Taş/sert yüzey yazıtları', 'Papirüsleri', 'El yazması kitapları'], answer: 1 },
  { id: 35, question: 'Truva kazılarını başlatan tartışmalı isim?', options: ['Wilhelm Dörpfeld', 'Heinrich Schliemann', 'Manfred Korfmann', 'Carl Blegen'], answer: 1 },
  { id: 36, question: 'Anadolu’da en eski yerleşik köy topluluğu?', options: ['Çatalhöyük', 'Hallan Çemi', 'Çayönü', 'Göbeklitepe'], answer: 1 },
  { id: 37, question: 'Bouleuterion ne amaçla kullanılır?', options: ['Ticaret merkezi', 'Meclis binası', 'Hamam', 'Kütüphane'], answer: 1 },
  { id: 38, question: 'Myken uygarlığında bindirme kubbeli mezar türü?', options: ['Tümülüs', 'Tholos', 'Lahit', 'Kurgan'], answer: 1 },
  { id: 39, question: 'Efes’te yedi harikadan biri sayılan yapı?', options: ['Celsus Kütüphanesi', 'Hadrian Tapınağı', 'Artemis Tapınağı', 'Büyük Tiyatro'], answer: 2 },
  { id: 40, question: 'Antik tiyatroda koronun bulunduğu yuvarlak alan?', options: ['Parodos', 'Orchestra', 'Diazoma', 'Analemma'], answer: 1 },
  { id: 41, question: 'Seramikte kırmızı/siyah renklenme temel olarak neyle ilgilidir?', options: ['Kireç miktarı', 'Demir oksit oranı', '1500°C üstü ısı', 'Yoğrulma biçimi'], answer: 1 },
  { id: 42, question: 'Arkaik Dönem erkek heykellerine ne denir?', options: ['Atlant', 'Kouros', 'Herm', 'Stele'], answer: 1 },
  { id: 43, question: 'Res Gestae Divi Augusti’nin en tam kopyası Türkiye’de nerede?', options: ['Ankara', 'Antalya', 'İzmir', 'Aydın'], answer: 0 },
  { id: 44, question: 'Sütun gövdesindeki dikey yivler?', options: ['Abakus', 'Kanelür', 'Sütun tamburu', 'Stylobat'], answer: 1 },
  { id: 45, question: 'Peripteros planlı tapınak neyi ifade eder?', options: ['Önde iki sütun', 'Ön-arka sütun dizisi', 'Dört yanı tek sıra sütun', 'Çift sıra sütun'], answer: 2 },
  { id: 46, question: 'Helenistik barok üslup en iyi hangi ekolde?', options: ['Rodos', 'Bergama', 'İskenderiye', 'Atina'], answer: 1 },
  { id: 47, question: 'Kültepe kazıları hangi bilim insanımızla özdeş?', options: ['Ekrem Akurgal', 'Tahsin Özgüç', 'Halet Çambel', 'Muhibbe Darga'], answer: 1 },
  { id: 48, question: 'Bizans’ta kubbeyi kare altyapıya oturtan üçgen öğe?', options: ['Tonoz', 'Pandantif', 'Apsis', 'Narteks'], answer: 1 },
  { id: 49, question: 'Paleolitik mağara resimleri için yaygın teori?', options: ['Dekorasyon', 'Av büyüsü ve ritüel', 'Ticari kayıt', 'Sınır belirleme'], answer: 1 },
  { id: 50, question: 'UNESCO’ya en güncel eklenenlerden arkeolojik alan?', options: ['Gordion', 'Ani', 'Afrodisias', 'Bergama'], answer: 0 },
];
