export const QUIZ_BANK = [
  { id: 1, question: 'İnsanlık tarihinde "Neolitik Devrim" kavramını ilk kez ortaya atan bilim insanı kimdir?', options: ['Lewis Binford', 'V. Gordon Childe', 'Ian Hodder', 'Robert Braidwood'], answer: 1 },
  { id: 2, question: 'Anadolu’da "Obsidiyen" ticaretinin merkezi sayılan ve obsidiyen kaynaklarına yakınlığıyla bilinen Neolitik yerleşim hangisidir?', options: ['Çayönü', 'Aşıklı Höyük', 'Hacılar', 'Hallan Çemi'], answer: 1 },
  { id: 3, question: 'Göbeklitepe\'deki T biçimli dikilitaşların üzerindeki hayvan kabartmaları hangi dönem üslubunu yansıtır?', options: ['Epipaleolitik / Çanak Çömleksiz Neolitik A', 'Geç Neolitik', 'Kalkolitik', 'Erken Tunç Çağı'], answer: 0 },
  { id: 4, question: 'Mezopotamya’da yazının ilk kez kullanıldığı dönem aşağıdakilerden hangisidir?', options: ['Ubeyd', 'Uruk', 'Cemdet Nasr', 'Akad'], answer: 1 },
  { id: 5, question: 'Kültepe (Kaniş) tabletleri, Anadolu arkeolojisi için neden bir dönüm noktasıdır?', options: ['İlk tapınak planlarını içermesi', 'Anadolu’nun yazılı tarihe geçişini sağlaması', 'Hitit İmparatorluğu\'nun başkentini belirtmesi', 'Demir kullanımını tarif etmesi'], answer: 1 },
  { id: 6, question: 'Hitit devlet yapısında kralın yetkilerini denetleyen soylular meclisine ne ad verilir?', options: ['Tavananna', 'Pankuş', 'Labarna', 'Ziti'], answer: 1 },
  { id: 7, question: '"Urartu" devletinin başkenti Tuşpa, günümüzdeki hangi şehirdedir?', options: ['Erzurum', 'Van', 'Kars', 'Erzincan'], answer: 1 },
  { id: 8, question: 'Frig sanatında sıkça görülen, ahşap işçiliği ve mobilyacılıkta kullanılan geçme tekniğine ne denir?', options: ['Fibula', 'Tümülüs', 'Mevduat', 'Kakmacılık / Kündekari (benzeri antik teknik)'], answer: 3 },
  { id: 9, question: 'Lidya Krallığı\'nın başkenti Sardes\'te (Sart) bulunan ve elektrumdan basılan ilk sikkelerin temel amacı neydi?', options: ['Halkın zenginleşmesi', 'Paralı askerlerin ödemelerini standartlaştırmak', 'Dış ticareti durdurmak', 'Tapınak vergilerini toplamak'], answer: 1 },
  { id: 10, question: 'Geç Hitit Devletleri döneminde görülen, kapı girişlerini koruyan aslan veya sfenks heykellerine ne ad verilir?', options: ['Megaron', 'Ortostat', 'Stela', 'Karum'], answer: 1 },
  { id: 11, question: 'Yunan tapınak mimarisinde, sütun başlığının hemen üzerinde yer alan yatay mimari öğeye ne denir?', options: ['Arşitrav (Epistil)', 'Friz', 'Geison', 'Timpanon'], answer: 0 },
  { id: 12, question: 'Dor düzeninde, metoplar arasında kalan ve üç dikey yivden oluşan bölüme ne ad verilir?', options: ['Volüt', 'Triglif', 'Abakus', 'Echinus'], answer: 1 },
  { id: 13, question: '"Kontrapost" (Contrapposto) duruş tekniğinin en erken ve en ünlü örneklerinden biri kabul edilen heykel hangisidir?', options: ['Kouros', 'Kritios Oğlu', 'Doryphoros', 'Laocoön'], answer: 1 },
  { id: 14, question: 'Helenistik Dönem\'in başlangıcı olarak kabul edilen olay hangisidir?', options: ['Peloponnesos Savaşları\'nın bitişi', 'Büyük İskender\'in ölümü (MÖ 323)', 'Augustus\'un imparator olması', 'Perslerin Yunanistan\'ı işgali'], answer: 1 },
  { id: 15, question: 'Roma mimarisinde, harç ve mırç kullanılarak elde edilen "Antik Beton"un adı nedir?', options: ['Opus Reticulatum', 'Opus Caementicium', 'Opus Sectile', 'Opus Tessellatum'], answer: 1 },
  { id: 16, question: 'Bir Roma tiyatrosunda seyircilerin oturduğu basamaklı kısma ne ad verilir?', options: ['Orchestra', 'Skene', 'Cavea', 'Vomitorium'], answer: 2 },
  { id: 17, question: 'Atina Akropolisi\'nde bulunan ve kadın figürlü sütunlara (Karyatid) sahip olan tapınak hangisidir?', options: ['Parthenon', 'Erechtheion', 'Nike Tapınağı', 'Propylaia'], answer: 1 },
  { id: 18, question: 'Roma şehir planlamasında kuzey-güney doğrultulu ana caddeye ne ad verilir?', options: ['Decumanus Maximus', 'Cardo Maximus', 'Forum', 'Insula'], answer: 1 },
  { id: 19, question: 'Seramik sanatında "Siyah Figür" tekniğinden "Kırmızı Figür" tekniğine geçiş yaklaşık olarak ne zaman gerçekleşmiştir?', options: ['MÖ 7. yüzyıl sonu', 'MÖ 530 civarı', 'MÖ 4. yüzyıl', 'MS 1. yüzyıl'], answer: 1 },
  { id: 20, question: 'Pompeii duvar resimlerinde "İllüzyonist" (Mimari) üslup kaçıncı stil olarak bilinir?', options: ['1. Stil', '2. Stil', '3. Stil', '4. Stil'], answer: 1 },
  { id: 21, question: '"Tabakalaşma Yasası"na (Law of Superposition) göre bir kazıda en alt tabakadaki buluntular için ne söylenebilir?', options: ['En modern tabakadır.', 'En eski tabakadır.', 'Tarihlendirilemezler.', 'Kesinlikle Roma dönemine aittir.'], answer: 1 },
  { id: 22, question: 'Dendrokronoloji yöntemi hangi materyal üzerinde tarihlendirme yapar?', options: ['Kemik', 'Seramik', 'Ağaç halkaları', 'Taş'], answer: 2 },
  { id: 23, question: 'Karbon-14 (C14) tarihlendirme yöntemi en fazla kaç yıla kadar sağlıklı sonuç verir?', options: ['5.000 yıl', '50.000 - 60.000 yıl', '1 milyon yıl', '10 milyon yıl'], answer: 1 },
  { id: 24, question: '"Süreçsel Arkeoloji"nin (New Archaeology) öncüsü kabul edilen ve arkeolojinin bir bilim olması gerektiğini savunan isim kimdir?', options: ['Ian Hodder', 'Lewis Binford', 'Heinrich Schliemann', 'Arthur Evans'], answer: 1 },
  { id: 25, question: 'Bir arkeolojik yüzey araştırmasında, seramik yoğunluğuna göre yerleşim sınırlarını belirlemek için kullanılan yönteme ne denir?', options: ['Sondaj', 'Survey (Sistematik Yüzey Araştırması)', 'Stratigrafi', 'Tipoloji'], answer: 1 },
  { id: 26, question: 'Taş alet teknolojisinde, bir çekirdekten önceden planlanmış formda yonga çıkarma tekniğine ne ad verilir?', options: ['Levallois tekniği', 'El baltası tekniği', 'Mikrolit tekniği', 'Baskı tekniği'], answer: 0 },
  { id: 27, question: '"In-situ" terimi arkeolojide neyi ifade eder?', options: ['Buluntunun laboratuvar ortamında incelenmesini', 'Buluntunun bulunduğu orijinal konumda olması', 'Buluntunun sahte olması', 'Yüzeyden toplanan dağınık malzemeyi'], answer: 1 },
  { id: 28, question: 'Su altı arkeolojisinin babası kabul edilen ve Gelidonya Burnu batığı kazısını yöneten isim kimdir?', options: ['Robert Ballard', 'George Bass', 'Jacques Cousteau', 'Cemal Pulak'], answer: 1 },
  { id: 29, question: 'Seramiklerin form ve bezeme özelliklerine göre gruplandırılmasına ne ad verilir?', options: ['Epigrafi', 'Tipoloji', 'Numismatik', 'Antropoloji'], answer: 1 },
  { id: 30, question: 'Post-Süreçsel (Art-Süreçsel) arkeoloji akımının en önemli savunucusu ve Çatalhöyük kazılarının eski başkanı kimdir?', options: ['James Mellaart', 'Ian Hodder', 'Colin Renfrew', 'Michael Schiffer'], answer: 1 },
  { id: 31, question: 'Roma mitolojisinde Yunan tanrısı Hermes\'in karşılığı hangisidir?', options: ['Mars', 'Merkür', 'Neptün', 'Jüpiter'], answer: 1 },
  { id: 32, question: 'Sikke üzerindeki yazılara ne ad verilir?', options: ['Epigraf', 'Lejand', 'Kabartma', 'Mühür'], answer: 1 },
  { id: 33, question: 'Bir sikkenin ön yüzüne (baş tarafı) numismatikte ne denir?', options: ['Revers', 'Avers', 'Exergue', 'Kondisyon'], answer: 1 },
  { id: 34, question: 'Epigrafi bilimi neyi inceler?', options: ['Sikkeleri', 'Taş ve sert yüzeyler üzerindeki yazıtları', 'Papirüsleri', 'El yazması kitapları'], answer: 1 },
  { id: 35, question: 'Truva (Troia) kazılarını başlatan ve Priamos\'un hazinelerini bulduğunu iddia eden tartışmalı isim kimdir?', options: ['Wilhelm Dörpfeld', 'Heinrich Schliemann', 'Manfred Korfmann', 'Carl Blegen'], answer: 1 },
  { id: 36, question: 'Anadolu’da bulunan en eski yerleşik köy topluluğu hangisidir?', options: ['Çatalhöyük', 'Hallan Çemi', 'Çayönü', 'Göbeklitepe'], answer: 1 },
  { id: 37, question: '"Bouleuterion" antik kentlerde hangi amaçla kullanılır?', options: ['Ticaret merkezi', 'Meclis binası', 'Hamam', 'Kütüphane'], answer: 1 },
  { id: 38, question: 'Myken uygarlığına özgü, bindirme teknikli kubbe yapısına sahip mezarlara ne denir?', options: ['Tümülüs', 'Tholos', 'Lahit', 'Kurgan'], answer: 1 },
  { id: 39, question: 'Efes Antik Kenti\'nde bulunan ve antik dünyanın yedi harikasından biri sayılan yapı hangisidir?', options: ['Celsus Kütüphanesi', 'Hadrian Tapınağı', 'Artemis Tapınağı', 'Büyük Tiyatro'], answer: 2 },
  { id: 40, question: 'Bir antik tiyatroda koronun bulunduğu yuvarlak alana ne denir?', options: ['Parodos', 'Orchestra', 'Diazoma', 'Analemma'], answer: 1 },
  { id: 41, question: 'Seramik fırınlanırken oksijenli ortamda kırmızı, oksijensiz ortamda siyah renk almasına neden olan kimyasal süreç neyle ilgilidir?', options: ['Kilin içindeki kireç miktarı', 'Kilin içindeki demir oksit oranı', 'Isının derecesi (1500°C üstü)', 'Kilin yoğrulma biçimi'], answer: 1 },
  { id: 42, question: 'Arkaik Dönem kadın heykellerine "Kore" denirken, erkek heykellerine ne denir?', options: ['Atlant', 'Kouros', 'Herm', 'Stele'], answer: 1 },
  { id: 43, question: 'Roma İmparatoru Augustus’un başarılarını anlatan "Res Gestae Divi Augusti" yazıtının en tam kopyası Türkiye’de nerededir?', options: ['Ankara (Augustus Tapınağı)', 'Antalya (Perge)', 'İzmir (Efessos)', 'Aydın (Aphrodisias)'], answer: 0 },
  { id: 44, question: 'Bir sütunun gövdesinde açılan dikey yivlere ne ad verilir?', options: ['Abakus', 'Kanelür', 'Sütun tamburu', 'Stylobat'], answer: 1 },
  { id: 45, question: '"Peripteros" planlı bir tapınak neyi ifade eder?', options: ['Önünde iki sütun bulunan tapınağı', 'Sadece ön ve arkada sütun dizisi olan tapınağı', 'Dört bir yanı tek sıra sütun dizisiyle çevrili tapınağı', 'Çift sıra sütun dizisiyle çevrili tapınağı'], answer: 2 },
  { id: 46, question: 'Helenistik dönem heykel sanatının "Barok" üslubu en iyi hangi ekolde görülür?', options: ['Rodos Ekolü', 'Bergama (Pergamon) Ekolü', 'İskenderiye Ekolü', 'Atina Ekolü'], answer: 1 },
  { id: 47, question: '"Kültepe (Kaniş)" kazıları hangi bilim insanımızla özdeşleşmiştir?', options: ['Ekrem Akurgal', 'Tahsin Özgüç', 'Halet Çambel', 'Muhibbe Darga'], answer: 1 },
  { id: 48, question: 'Bizans mimarisinde kubbeyi kare bir altyapı üzerine oturtmaya yarayan üçgen geçiş öğesine ne ad verilir?', options: ['Tonoz', 'Pandantif', 'Apsis', 'Narteks'], answer: 1 },
  { id: 49, question: 'Paleolitik Çağ’da mağara duvarlarına yapılan resimlerin temel motivasyonu hakkında en yaygın teori hangisidir?', options: ['Dekorasyon amaçlı olması', 'Av büyüsü ve ritüel', 'Ticari kayıt tutma', 'Sınır belirleme'], answer: 1 },
  { id: 50, question: 'Türkiye\'nin UNESCO Dünya Mirası Listesi\'ndeki en son (veya en güncel eklenenlerden) arkeolojik alanlarından biri hangisidir?', options: ['Gordion', 'Ani Arkeolojik Alanı', 'Afrodisias', 'Bergama'], answer: 0 },

  { id: 51, question: 'Antik sikkelerin ön yüzüne (genellikle kafa olan taraf) ne denir?', options: ['Revers', 'Avers', 'Lejand', 'Exergue'], answer: 1 },
  { id: 52, question: 'Sikke üzerinde bulunan ve darphaneyi veya basan kişiyi temsil eden küçük işarete ne denir?', options: ['Amblem', 'Monogram', 'Kontrmark', 'Flann'], answer: 1 },
  { id: 53, question: 'Sert yüzeyler (taş, metal, seramik) üzerindeki yazıları inceleyen bilim dalı nedir?', options: ['Paleografi', 'Epigrafi', 'Papiroloji', 'Heraldik'], answer: 1 },
  { id: 54, question: 'Bizans mimarisinde kubbeyi kare planlı bir alt yapıya oturtmak için kullanılan üçgen geçiş elemanına ne denir?', options: ['Tonoz', 'Pandantif', 'Apsis', 'Narteks'], answer: 1 },
  { id: 55, question: 'Erken Hristiyan mimarisinde, bazilikaların giriş kısmındaki ön bölüme (avluya) ne denir?', options: ['Naos', 'Atrium / Narteks', 'Bema', 'Transept'], answer: 1 },
  { id: 56, question: '"İkonoklazm" dönemi neyi ifade eder?', options: ['Kiliselerin inşasını', 'Tasvir (ikon) kırıcılığı ve yasaklanmasını', 'Yeni bir devlet kurulmasını', 'Haçlı seferlerini'], answer: 1 },
  { id: 57, question: 'Ayasofya’nın (Hagia Sophia) mimarları kimlerdir?', options: ['Sinan ve Davud', 'Anthemios ve Isidoros', 'Vitruvius ve Apollodoros', 'Callicrates ve Ictinus'], answer: 1 },
  { id: 58, question: 'Bir sikkenin ağırlığının düşürülmesi veya içine değersiz metal karıştırılması işlemine ne denir?', options: ['Enflasyon', 'Tağşiş', 'Reform', 'Emisyon'], answer: 1 },
  { id: 59, question: 'Bir yapının dış cephesinde, pencere veya kapı üzerindeki yarım dairelik bezemeli alana ne denir?', options: ['Alınlık', 'Timpanon (veya Lünet)', 'Arşitrav', 'Friz'], answer: 1 },
  { id: 60, question: 'Mozaik sanatında kullanılan her bir küçük renkli taş parçasına ne ad verilir?', options: ['Emblem', 'Tessera', 'Opus', 'Figür'], answer: 1 },
  { id: 61, question: 'Efes Antik Kenti’ndeki Celcus Kütüphanesi aslında ne amaçla inşa edilmiştir?', options: ['Sadece bir kütüphane', 'Vali Celcus adına bir anıt mezar (Heroon)', 'Bir tapınak', 'Belediye binası'], answer: 1 },
  { id: 62, question: 'Türkiye’nin ilk su altı arkeolojik kazısı nerede yapılmıştır?', options: ['Kaş - Uluburun', 'Gelidonya Burnu', 'Yassıada', 'Tekirdağ'], answer: 1 },
  { id: 63, question: '"Troia" (Truva) antik kentinde kaç tane ana yerleşim tabakası vardır?', options: ['3', '5', '9', '12'], answer: 2 },
  { id: 64, question: 'Homeros’un İlyada destanında anlatılan Troia savaşı muhtemelen hangi tabakada gerçekleşmiştir?', options: ['Troia I', 'Troia II', 'Troia VI veya VIIa', 'Troia IX'], answer: 2 },
  { id: 65, question: 'Mısır hiyerogliflerini çözen dilbilimci kimdir?', options: ['Howard Carter', 'Jean-François Champollion', 'Heinrich Schliemann', 'Arthur Evans'], answer: 1 },
  { id: 66, question: 'Dünyanın en eski batığı olarak bilinen batık hangisidir?', options: ['Gelidonya', 'Uluburun', 'Kyrenia (Girne)', 'Titanic'], answer: 1 },
  { id: 67, question: 'Bir antik tiyatroda koronun dans ettiği ve şarkı söylediği yuvarlak alana ne denir?', options: ['Skene', 'Orchestra', 'Parodos', 'Analemma'], answer: 1 },
  { id: 68, question: '"Güneşin doğduğu yer" anlamına gelen ve Anadolu için kullanılan terim hangisidir?', options: ['Mesopotamia', 'Anatolia', 'Levant', 'Thrace'], answer: 1 },
  { id: 69, question: 'Arkaik dönem erkek heykellerine "Kouros" denirken, giyinik kadın heykellerine ne denir?', options: ['Karyatid', 'Kore', 'Amazon', 'Nike'], answer: 1 },
  { id: 70, question: 'Roma’daki "Pantheon" tapınağının en büyük özelliği nedir?', options: ['Dünyanın en büyük mermer tapınağı olması', 'Devasa bir beton kubbe ve tepesinde açıklık (oculus) bulunması', 'İki katlı olması', 'Tamamen ahşaptan yapılması'], answer: 1 },
  { id: 71, question: 'İlk parayı basan uygarlık hangisidir?', options: ['Sümerler', 'Hititler', 'Lidyalılar', 'Romalılar'], answer: 2 },
  { id: 72, question: 'MÖ 333 yılında Büyük İskender ile Pers kralı III. Darius arasında Hatay yakınlarında gerçekleşen savaş hangisidir?', options: ['Granikos', 'Issos', 'Gaugamela', 'Maraton'], answer: 1 },
  { id: 73, question: '"Stoa" mimari yapısı neyi ifade eder?', options: ['Bir tapınağı', 'Sütunlu, üstü kapalı yürüyüş yolunu / galeriyi', 'Meclis binasını', 'Spor salonunu'], answer: 1 },
  { id: 74, question: 'Myken uygarlığının en meşhur kapısı hangisidir?', options: ['İştar Kapısı', 'Aslanlı Kapı', 'Kral Kapısı', 'Hadrian Kapısı'], answer: 1 },
  { id: 75, question: '"Sutton Hoo" buluntuları hangi kültüre aittir?', options: ['Viking', 'Anglo-Sakson', 'Kelt', 'Roma'], answer: 1 },
  { id: 76, question: 'Bir kazıda seramiğin fırınlanma derecesini anlamak için yapılan analize ne denir?', options: ['Petroğrafi', 'Termolüminesans', 'Karbon-14', 'OSL'], answer: 0 },
  { id: 77, question: '"Kültepe Tabletleri" hangi dilde yazılmıştır?', options: ['Hititçe', 'Asurca (Eski Asur Lehçesi)', 'Sümerce', 'Akadca'], answer: 1 },
  { id: 78, question: '"Bouleuterion" antik kentlerde hangi işlev için kullanılır?', options: ['Dinlenme', 'Şehir Meclisi toplantıları', 'Ticari depolar', 'Tapınım törenleri'], answer: 1 },
  { id: 79, question: 'Yunan tapınaklarında tanrının heykelinin bulunduğu ana odaya ne denir?', options: ['Pronaos', 'Naos (veya Cella)', 'Opisthodomos', 'Adyton'], answer: 1 },
  { id: 80, question: 'Bir Roma askeri kampına (Castrum) verilen genel ad nedir?', options: ['Villa', 'Praetorium', 'Castra', 'Basilica'], answer: 2 },
  { id: 81, question: '"Göbeklitepe"yi dünya arkeolojisine kazandıran ve kazı başkanlığını yürüten (vefat eden) Alman arkeolog kimdir?', options: ['Harald Hauptmann', 'Klaus Schmidt', 'Ricardo Eichmann', 'Peter Neve'], answer: 1 },
  { id: 82, question: 'İlk organize kütüphaneyi kuran Asur kralı kimdir?', options: ['Sargon', 'Asurbanipal', 'Hammurabi', 'Nabukadnezar'], answer: 1 },
  { id: 83, question: 'Anadolu’daki en büyük tümülüs hangisidir?', options: ['Midas Tümülüsü', 'Alyattes Tümülüsü (Lidya)', 'Nemrut Dağı Tümülüsü', 'Karun Hazinesi Tümülüsü'], answer: 1 },
  { id: 84, question: '"Arkeolojik Yüzey Araştırması"na literatürde ne denir?', options: ['Excavation', 'Survey', 'Restoration', 'Conservation'], answer: 1 },
  { id: 85, question: '"Klazomenai" (Urla) antik kenti hangi sanayi dalındaki antik üretimiyle ünlüdür?', options: ['Şarap', 'Zeytinyağı', 'Tekstil', 'Cam'], answer: 1 },
  { id: 86, question: 'Arkeolojide "Maddi Kültür" (Material Culture) neyi kapsar?', options: ['Sadece paraları', 'Sadece yazılı metinleri', 'İnsanlar tarafından üretilmiş veya değiştirilmiş her türlü nesneyi', 'Sadece mermer heykelleri'], answer: 2 },
  { id: 87, question: 'Roma döneminde ölülerin yakılması geleneğine ne denir?', options: ['İnhumasyon', 'Kremasyon', 'Mumyalama', 'Defne'], answer: 1 },
  { id: 88, question: '"Laocoön ve Oğulları" heykeli hangi dönemin karakteristik özelliklerini taşır?', options: ['Klasik', 'Arkaik', 'Helenistik', 'Roma Klasisizmi'], answer: 2 },
  { id: 89, question: 'Milas yakınlarında bulunan ve Karia Satrabı Hekatomnos’a ait olan anıt mezar neresidir?', options: ['Uzunyuva', 'Belevi', 'Gümüşkesen', 'Labraunda'], answer: 0 },
  { id: 90, question: 'Nemrut Dağı’ndaki dev heykelleri yaptıran Kommagene kralı kimdir?', options: ['I. Antiochos', 'Mithridates', 'II. Eumenes', 'Attalos'], answer: 0 },
  { id: 91, question: 'Bir mermer heykelin yüzeyindeki "patina" nedir?', options: ['Bir tür çatlak', 'Zamanla oluşan doğal koruyucu tabaka / renk değişimi', 'Yapay boya', 'Mermerin damarı'], answer: 1 },
  { id: 92, question: '"Epigrafi" uzmanına ne ad verilir?', options: ['Epigrafist', 'Epigraf', 'Paleograf', 'Filolog'], answer: 1 },
  { id: 93, question: 'Arkeolojide "Etnografik Analoji" ne demektir?', options: ['Kazıdan çıkan kemikleri incelemek', 'Günümüzdeki geleneksel toplumları gözlemleyerek geçmişteki yaşamı anlamaya çalışmak', 'Sadece antik yazarları okumak', 'Toprağın rengine göre tabaka belirlemek'], answer: 1 },
  { id: 94, question: '"Çingene Kızı" mozaiği hangi antik kentten çıkarılmıştır?', options: ['Efes', 'Zeugma', 'Antakya', 'Bergama'], answer: 1 },
  { id: 95, question: 'İskender Lahdi hangi antik kentteki kraliyet nekropolünden çıkarılmıştır?', options: ['İstanbul', 'Sayda (Sidon)', 'İskenderiye', 'Atina'], answer: 1 },
  { id: 96, question: 'Dünyanın en büyük mozaik müzesi hangisidir?', options: ['Zeugma Mozaik Müzesi', 'Hatay Arkeoloji Müzesi', 'Bardo Müzesi', 'Napoli Müzesi'], answer: 1 },
  { id: 97, question: 'Bir antik kentin çevresini saran sur duvarlarına ne ad verilir?', options: ['Peristasis', 'Temenos', 'Tahkimat (Fortification)', 'Podros'], answer: 2 },
  { id: 98, question: 'Mezopotamya’da "Enuma Eliş" neyi anlatır?', options: ['Tufan hikayesini', 'Yaratılış destanını', 'Gilgamış’ın maceralarını', 'Bir kralın yasalarını'], answer: 1 },
  { id: 99, question: '"Arkeometri" ne ile uğraşır?', options: ['Kazı tekniklerini geliştirir', 'Pozitif bilimlerin (fizik, kimya, biyoloji) yöntemlerini arkeolojiye uygular', 'Sadece heykel sanatını inceler', 'Antik dilleri çevirir'], answer: 1 },
  { id: 100, question: 'Bir antik kentin "kutsal alanı"na ne ad verilir?', options: ['Agora', 'Temenos', 'Nekropol', 'Gymnasion'], answer: 1 },

];
